In [2]:
import torch

print('torch version', torch.__version__)

torch version 2.7.1


In [3]:
## intro to Tensor
### creating tensor
#### Scalar
scalar = torch.tensor(7)
scalar
scalar.ndim
## get tensor cack as Python int
scalar.item()
# scalar[0]   # invalid for 0-d

7

In [19]:
# Vector
vector = torch.tensor([4,4])
vector
vector.shape
vector.ndim
vector[1]

tensor(4)

In [23]:
## Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX[1]
MATRIX.shape

torch.Size([2, 2])

In [25]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [26]:
TENSOR.ndim

3

In [27]:
TENSOR.shape

torch.Size([1, 3, 3])

In [67]:
TENSOR[0,1]

tensor([3, 6, 9])

In [58]:
TENSOR[0,1,1]

tensor(6)

In [61]:
T = TENSOR[[0]]
T.ndim

3

In [54]:
import numpy as np
arr = np.array([[[0,1,3],
                 [1,5,8],
                 [6,9,4]]])
arr.ndim
arr.shape
arr[0][1][2]
arr[0,1,2]

np.int64(8)

In [72]:
# Random Tensor
rand = torch.rand(3,2)
rand
rand.shape
rand.ndim

2

In [74]:
# create a rand tensor with similar shape to img tensor
rand_img_size_tensor = torch.rand(224,224, 3) # H, W and colour chanels
rand_img_size_tensor.shape, rand_img_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
##Tensor of zeroes or Ones or Identity
zeros = torch.zeros(3, 4)
zeros
ones = torch.ones(3, 2)
ones
identity = torch.eye(3)
identity

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [20]:
# Creat range
rang = torch.arange(1,11,1)
rang

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
## creating tensors like

ten_zeros = torch.zeros_like(rang)  # creat same tensor like above but with all zero ellemnts
ten_ones = torch.ones_like(rang)  # creat same tensor like above but with all one ellemnts
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
## Float tensor 
float_tensor = torch.tensor([1.0, 2.0, 3.0],
                             dtype=torch.float32)
float_tensor

tensor([1., 2., 3.])

In [31]:
tensr = torch.tensor([1, 2, 3])
tensr + 5

tensor([6, 7, 8])

In [ ]:
# Matrix multiplication (dot product)
# element-wise multiplication
tens1 = torch.tensor([[1, 2], [3, 4]])
tens2 = torch.tensor([[5, 6], [7, 8]])

mult = torch.matmul(tens1, tens2)  # more commonly used
## or equivalently
mult = torch.mm(tens1, tens2)
## or equivalently
mult = tens1 @ tens2
mult

tensor([[19, 22],
        [43, 50]])

In [43]:
## transpose of a tensor
transpose_tens1 = tens1.t()
tens1, transpose_tens1, tens1.T

(tensor([[1, 2],
         [3, 4]]),
 tensor([[1, 3],
         [2, 4]]),
 tensor([[1, 3],
         [2, 4]]))

In [ ]:
### Find Matrix min, max, mean, sum, etc. (tensor aggregation)
x = torch.arange(1, 100, 10)

torch.min(x), torch.max(x), torch.sum(x)
x.min()
torch.mean(x.float())  ## torch func requires float tensor
# or equivalently
x.float().mean()




tensor(46.)

In [50]:
### Finding the position of elements
x1 = torch.arange(3, 100, 10)
# find the index position that element has min value
x_indx = x1.argmin()
x_indx

tensor(0)

In [ ]:
### reshape, squeeze, unsqueeze and stack tensors
# view - return a new tensor with the same data but different shape
# squeeze - remove all dimensions of size 1
# unsqueeze - add a dimension of size 1
# stack - combine multiple tensors on top/side of each other
# permute - change the order of dimensions


In [57]:
import torch
x = torch.arange(1., 11.)
x , x.shape


(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
# add an extra dimension
x_reshaped = x.reshape(1,10)  # or (2,5) or (10,1) 

x_reshaped.shape, x.shape
x_reshaped

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [65]:
# change a view
x_view = x.view(2, 5)
x_view

# changing x_view causes x to be changed as well
x_view[1, 3] = 99
x, x_view

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 99., 10.]),
 tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8., 99., 10.]]))

In [80]:
# stack tensor on top of another tensor
z = torch.arange(1., 11.)
z_stacked = torch.stack([x, x,x], dim=1)
z_stacked

tensor([[ 1.,  1.,  1.],
        [ 2.,  2.,  2.],
        [ 3.,  3.,  3.],
        [ 4.,  4.,  4.],
        [ 5.,  5.,  5.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  7.],
        [ 8.,  8.,  8.],
        [99., 99., 99.],
        [10., 10., 10.]])

In [95]:
## squeeze and unsqueeze
y = torch.arange(1., 11.).reshape(10,1)
y_squeez = y.squeeze()   # or torch.squeeze(y)
y.shape , y_squeez.shape   # it removes the dimension of size 1
y_unsqueez = y_squeez.unsqueeze(0)   # 
y_unsqueez.shape    


torch.Size([1, 10])

In [ ]:
## torch.permute rearranging dimensions of tensors
x_original = torch.rand(224, 223, 3)   

# permute the original tensor to rearrange the axis (or dimensions) order
x_permuted = x_original.permute(2, 0, 1)  # Shift axis (0 ->2, 1 -> 2, 2 -> 1)

print(f'original shape: {x_original.shape}')
print(f'permuted shape: {x_permuted.shape}')

## permute is a view of the original tensor- it does not create a copy

original shape: torch.Size([224, 223, 3])
permuted shape: torch.Size([3, 224, 223])


In [99]:
### indexing - selecting elements from a tensor
### it is similar to numpy indexing

import torch
x = torch.arange(1, 10).reshape(1,3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]  # on the first bracket gives us the 0 th element- target the outer bracket

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# lets index on the middle braket (dim =1 )
x[0,0]  # give us the 0 th element of the middle tensor - target the first  0 then the first 0 of the second


tensor([1, 2, 3])

In [ ]:
# lets index on the last bracket (dim =2 )
# target 0 th element of the first bracket, then the first element of the 2 and the first elemnt of the bracket
x[0,0,0]   # give us the 0 th element of the last tensor

tensor(1)

In [107]:
x[0,:,0]

tensor([1, 4, 7])

In [112]:
# index on x to return 3, 6, 9
x[0,:,2]


tensor([3, 6, 9])

In [ ]:
# PyTorch tensors vs NumPy arrays

# numpy array to PyTorch tensor
import numpy as np
import torch 
array = np.array([1, 2, 3] )

tensor = torch.from_numpy(array) # or tensor = torch.tensor(array)

array, tensor

(array([1, 2, 3]), tensor([1, 2, 3]))

In [124]:
# tensor to numpy array
tensor = torch.ones(3)
numpy_arr = tensor.numpy()

In [134]:
# reproducibility
torch.manual_seed(42)
torch.rand(3,2)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009]])

In [136]:
#Running tensors and Pytorch objects on the GPU
# !nvidia-smi    ### try on colab!
torch.cuda.is_available()
# device agnostic code
device = torch.device("cuda" if torch.cuda.is_available() else "cpu") 
device

device(type='cpu')

In [35]:
import torch

x = torch.tensor([[1, 2],
                 [3, 4]])
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [40]:
# add an extra dimension to x
x = x.reshape(1, 9)
x.shape

torch.Size([1, 9])

In [41]:
# change the view
z = x.view(3, 3)  # share the same memory with x (change z will change x)
z.shape

torch.Size([3, 3])

In [44]:
# stack tensor of top each other
x = x.reshape(9, 1)
x_stacked = torch.stack([x,x,x], dim=1)
x_stacked.shape

torch.Size([9, 3, 1])

In [48]:
# remove all single dims from target tensor
x_stacked = x_stacked.squeeze()
x_stacked.shape

torch.Size([9, 3])

In [53]:
# add an extra dimension to x
x = x.unsqueeze(dim=0)
x.shape

torch.Size([1, 9])

In [56]:
# make some random tensor but reproducible
torch.manual_seed(42)
x = torch.rand(2,2)
x

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])

In [59]:
# device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
x = x.to(device)   # move tensor to the selected device (if available)
x.device

device(type='cpu')

In [60]:
# note numpy array dosnt work with GPU
# bring back tensor to CPU 
tensor_on_cpu = x.cpu().numpy()
