In [2]:
import torch

print('torch version', torch.__version__)

torch version 2.7.1


In [3]:
## intro to Tensor
### creating tensor
#### Scalar
scalar = torch.tensor(7)
scalar
scalar.ndim
## get tensor cack as Python int
scalar.item()
# scalar[0]   # invalid for 0-d

7

In [19]:
# Vector
vector = torch.tensor([4,4])
vector
vector.shape
vector.ndim
vector[1]

tensor(4)

In [23]:
## Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX[1]
MATRIX.shape

torch.Size([2, 2])

In [25]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [26]:
TENSOR.ndim

3

In [27]:
TENSOR.shape

torch.Size([1, 3, 3])

In [67]:
TENSOR[0,1]

tensor([3, 6, 9])

In [58]:
TENSOR[0,1,1]

tensor(6)

In [61]:
T = TENSOR[[0]]
T.ndim

3

In [54]:
import numpy as np
arr = np.array([[[0,1,3],
                 [1,5,8],
                 [6,9,4]]])
arr.ndim
arr.shape
arr[0][1][2]
arr[0,1,2]

np.int64(8)

In [72]:
# Random Tensor
rand = torch.rand(3,2)
rand
rand.shape
rand.ndim

2

In [74]:
# create a rand tensor with similar shape to img tensor
rand_img_size_tensor = torch.rand(224,224, 3) # H, W and colour chanels
rand_img_size_tensor.shape, rand_img_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
##Tensor of zeroes or Ones or Identity
zeros = torch.zeros(3, 4)
zeros
ones = torch.ones(3, 2)
ones
identity = torch.eye(3)
identity

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [20]:
# Creat range
rang = torch.arange(1,11,1)
rang

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
## creating tensors like

ten_zeros = torch.zeros_like(rang)  # creat same tensor like above but with all zero ellemnts
ten_ones = torch.ones_like(rang)  # creat same tensor like above but with all one ellemnts
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
## Float tensor 
float_tensor = torch.tensor([1.0, 2.0, 3.0],
                             dtype=torch.float32)
float_tensor

tensor([1., 2., 3.])

In [31]:
tensr = torch.tensor([1, 2, 3])
tensr + 5

tensor([6, 7, 8])

In [ ]:
# Matrix multiplication (dot product)
# element-wise multiplication
tens1 = torch.tensor([[1, 2], [3, 4]])
tens2 = torch.tensor([[5, 6], [7, 8]])

mult = torch.matmul(tens1, tens2)  # more commonly used
## or equivalently
mult = torch.mm(tens1, tens2)
## or equivalently
mult = tens1 @ tens2
mult

tensor([[19, 22],
        [43, 50]])

In [43]:
## transpose of a tensor
transpose_tens1 = tens1.t()
tens1, transpose_tens1, tens1.T

(tensor([[1, 2],
         [3, 4]]),
 tensor([[1, 3],
         [2, 4]]),
 tensor([[1, 3],
         [2, 4]]))

In [ ]:
### Find Matrix min, max, mean, sum, etc. (tensor aggregation)
x = torch.arange(1, 100, 10)

torch.min(x), torch.max(x), torch.sum(x)
x.min()
torch.mean(x.float())  ## torch func requires float tensor
# or equivalently
x.float().mean()




tensor(46.)

In [50]:
### Finding the position of elements
x1 = torch.arange(3, 100, 10)
# find the index position that element has min value
x_indx = x1.argmin()
x_indx

tensor(0)

In [ ]:
### reshape, squeeze, unsqueeze and stack tensors
# view - return a new tensor with the same data but different shape
# squeeze - remove all dimensions of size 1
# unsqueeze - add a dimension of size 1
# stack - combine multiple tensors on top/side of each other
# permute - change the order of dimensions


In [57]:
import torch
x = torch.arange(1., 11.)
x , x.shape


(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
# add an extra dimension
x_reshaped = x.reshape(1,10)  # or (2,5) or (10,1) 

x_reshaped.shape, x.shape
x_reshaped

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [65]:
# change a view
x_view = x.view(2, 5)
x_view

# changing x_view causes x to be changed as well
x_view[1, 3] = 99
x, x_view

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 99., 10.]),
 tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8., 99., 10.]]))

In [80]:
# stack tensor on top of another tensor
z = torch.arange(1., 11.)
z_stacked = torch.stack([x, x,x], dim=1)
z_stacked

tensor([[ 1.,  1.,  1.],
        [ 2.,  2.,  2.],
        [ 3.,  3.,  3.],
        [ 4.,  4.,  4.],
        [ 5.,  5.,  5.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  7.],
        [ 8.,  8.,  8.],
        [99., 99., 99.],
        [10., 10., 10.]])

In [90]:
## squeeze and unsqueeze
# y = torch.arange(1., 11.)
# y_squeez = y.squeeze()   # or torch.squeeze(y)
z_squeez = z_stacked.squeeze(0)   # or torch.squeeze(z_stacked)
z_squeez.shape
z_unsqueez = z_squeez.unsqueeze(0)   # or torch.unsqueeze(z_squeez)
z_unsqueez.shape    


torch.Size([1, 10, 3])